name: deploy-staging

on:
  push:
    branches:
      - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Nodejs setup
        uses: actions/setup-node@v3
        with:
          node-version: '20.0'

      - name: Go setup
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.0'

      - name: Install Serverless Framework
        run: npm install -g serverless@3
      
      - name: Update bootstrap file
        run: go build -o bootstrap .

      - name: Deploy to staging stage
        run: sls deploy function -f Serverless-Test --stage staging

        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
# to trigger commit